server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mi20030610.
    url: jdbc:mysql://localhost:3306/elm
  web:
    resources:
      static-locations: file:H:\\elmImg
  mvc:
    static-path-pattern: /static/**

  resources:
    static-locations: classpath:/

logging:
  level:
    root: warn
    com.kaven.mybatisplus.dao: trace
  pattern:
    console: '%p%m%n'

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

